export type Article = {
  slug: string;
  title: string;
  summary: string;
  body: string;
};

export const ARTICLES: Article[] = [
  {
    slug: 'presence-and-relaxation',
    title: 'Presence and Relaxation',
    summary: 'Two simple skills that make any breathing exercise work better: paying attention to now, and consciously softening the body.',
    body: 'Almost every breathing technique in this app is a physical pattern - a specific rhythm of inhale, hold, and exhale. But two much simpler skills sit underneath all of them and make a real difference to how well any pattern works: staying present, and relaxing the body.\n\nStaying present just means noticing the breath itself - the air at your nostrils, your chest or belly rising and falling - rather than thinking about your day while your body goes through the motions. Your attention will wander; that\'s normal and expected, not a failure. The practice isn\'t staying perfectly focused, it\'s noticing when you\'ve drifted and gently returning attention to the breath, over and over. That returning is the actual exercise.\n\nRelaxing the body matters because tension and breath are directly linked. A clenched jaw, raised shoulders, or tight hands tend to pull you into shallow chest breathing without you noticing, while a physically relaxed body makes slow diaphragmatic breathing almost automatic. Before starting any pattern, it\'s worth taking a few seconds to consciously unclench your jaw, drop your shoulders away from your ears, and let your hands go soft.\n\nCombined, these two habits turn a mechanical breathing count into something closer to genuine practice: a relaxed body breathing at its own steady rhythm, with your attention quietly along for the ride.',
  },
  {
    slug: 'autonomic-nervous-system',
    title: 'The Autonomic Nervous System',
    summary: 'The background system that runs your heart rate, digestion, and stress response - and how breath can influence it.',
    body: 'The autonomic nervous system (ANS) is the part of your nervous system that runs the body\'s background processes without you having to think about them: heart rate, digestion, pupil size, how much you sweat, and much more. It has two main branches that work in balance with each other.\n\nThe sympathetic branch is your "fight or flight" system - it ramps things up: faster heart rate, redirected blood flow to muscles, heightened alertness. The parasympathetic branch is your "rest and digest" system - it winds things down: slower heart rate, activated digestion, a general sense of calm. Neither is "good" or "bad"; you need both, shifting as the situation calls for it.\n\nHere\'s what makes breath special: nearly everything the ANS controls happens automatically, but breathing is a rare exception - it runs on autopilot most of the time, yet you can also take direct conscious control of it. That makes breath a kind of back door into a system you otherwise can\'t consciously touch.\n\nThis is the underlying reason different breathing patterns feel so different. A long, slow exhale (like in 4-7-8 or Cyclic Sighing) tends to nudge the parasympathetic system toward calm. Rapid, forceful breathing (like Wim Hof or Bhastrika-style techniques) tends to activate the sympathetic system toward alertness and energy. Neither is more "correct" - they\'re different tools for different moments.',
  },
  {
    slug: 'diaphragmatic-breathing',
    title: 'Diaphragmatic Breathing',
    summary: 'The foundational technique underneath almost every breathing exercise - breathing from your belly, not your chest.',
    body: 'The diaphragm is a large, dome-shaped muscle sitting just below your lungs. When you inhale, it should contract and flatten downward, drawing air deep into the lungs and pushing your belly outward. When you exhale, it relaxes back into its dome shape. This is diaphragmatic breathing, sometimes called belly breathing.\n\nMany people, especially under stress, shift instead toward shallow chest breathing - short breaths that raise the chest and shoulders while barely engaging the diaphragm at all. It\'s not inherently harmful in short bursts, but as a habitual pattern it tends to keep the body in a low-grade alert state, since shallow rapid breathing is itself a signal the sympathetic nervous system reads as "something\'s wrong."\n\nYou can check which one you\'re doing: lie down or sit comfortably, put one hand on your chest and one on your belly, and breathe normally. If the hand on your chest is doing most of the moving, that\'s chest breathing. If the hand on your belly rises and falls more than your chest, that\'s diaphragmatic breathing.\n\nThis technique isn\'t really a pattern of its own - it\'s the foundation underneath nearly every exercise in this app. Box Breathing, 4-7-8, Resonance Breathing, and the others all work best when each inhale and exhale is diaphragmatic rather than shallow. It\'s worth practicing on its own first: a few minutes of slow belly breathing, no counting or specific ratio, just noticing the breath move your belly rather than your chest.',
  },
  {
    slug: 'air-hunger',
    title: 'Air Hunger',
    summary: 'The mild, controlled urge to breathe that Buteyko Breathing deliberately cultivates.',
    body: 'Air hunger is the felt sense that you want to breathe - that gentle-to-urgent pull to take your next inhale. It\'s driven mainly by rising carbon dioxide (CO2) in your blood, not by falling oxygen as most people assume. Your body is exquisitely sensitive to CO2, and it\'s this sensitivity, not oxygen level, that usually decides when you feel you "need" a breath.\n\nThis is the whole premise behind Buteyko Breathing. Many people who breathe too much, too often - chronic over-breathers - become oversensitized to CO2 over time, so their body signals air hunger and breathlessness at levels of CO2 that are actually completely normal. This oversensitivity is linked to anxiety, breathlessness, and a general feeling of never quite getting a satisfying breath.\n\nButeyko\'s light breathing and post-exhale pause are designed to gently and gradually raise your tolerance to CO2, which in turn recalibrates that oversensitive alarm system. Over time, with consistent light practice, the same CO2 level that used to trigger breathlessness stops feeling urgent at all.\n\nThe key word throughout is mild. The air hunger you\'re aiming for in Buteyko is a light, background pull - noticeable, even slightly uncomfortable, but never gasping, straining, or panicked. If it tips into anything sharp or distressing, that\'s a sign to back off, breathe normally, and ease into it more gradually next time.',
  },
  {
    slug: 'hrv',
    title: 'Heart Rate Variability (HRV)',
    summary: 'Why the space between your heartbeats says more than your heart rate alone.',
    body: 'Your heart doesn\'t beat like a metronome. Even at a steady resting heart rate, the exact gap between one beat and the next varies slightly from beat to beat - that variation is Heart Rate Variability, or HRV.\n\nA higher HRV generally reflects a nervous system that can flexibly shift between alertness and calm as circumstances demand. A lower HRV can reflect stress, fatigue, illness, or overtraining, since it often means the body is stuck leaning on one setting rather than adapting smoothly. This is why HRV has become a popular recovery and readiness marker in fitness trackers and smartwatches.\n\nBreathing practice is one of the most direct ways to influence HRV in the moment. Slow, paced breathing - especially around 5-6 breaths per minute, close to what patterns like Resonance Breathing use - tends to increase HRV during the practice itself, and regular practice over time is associated with higher resting HRV. This happens because slow exhale-emphasized breathing engages the vagus nerve, the main channel through which your parasympathetic ("rest and digest") system talks to your heart.\n\nWorth keeping in perspective: HRV is one signal among many, it varies a lot between individuals, and a single low reading on a given day isn\'t a diagnosis of anything. It\'s most useful as a trend over time, not a single number to chase.',
  },
  {
    slug: 'ujjayi-how-to',
    title: 'How to Practice Ujjayi Breath',
    summary: 'Step-by-step guidance for the throat constriction that gives Ujjayi its signature ocean sound.',
    body: 'Ujjayi (pronounced oo-JAI) gets its "ocean breath" name from the soft, rushing sound it produces - here\'s how to actually create that sound and settle into the practice.\n\nStart seated comfortably with your spine tall and shoulders relaxed, breathing through your nose with your mouth closed throughout.\n\nTo find the sound, gently constrict the back of your throat - the same subtle tightening you\'d use to fog up a mirror with a "haaa," or to whisper. Keep your mouth closed and let that same soft constriction shape the air moving through your nose on both the inhale and the exhale.\n\nOnce the sound feels consistent, slow everything down. Lengthen each inhale and exhale evenly - aim for somewhere around 4 to 6 seconds each, matching the rhythm used in this app\'s Ujjayi Breath pattern. The sound should stay soft and smooth throughout, like distant ocean waves, not a hard or strained rasp.\n\nIf you lose the sound, or your throat starts to feel tight or strained, ease off the constriction and return to normal breathing for a few breaths before trying again - this should never feel forced.\n\nStart with just a minute or two of practice, building up gradually as the throat constriction becomes more natural and less effortful to hold.',
  },
];
